version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html

  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: php
    depends_on:
      - nginx
    volumes:
      - ./wordpress:/var/www/html

  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  wordpress:
    build: 
      context: .
      dockerfile: wordpress.dockerfile
    container_name: wordpress
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html